#!/usr/bin/env python3
def island_perimeter(grid):
    """
        returns the perimeter of the island 

        Args: grid[] it represents water by 0 and land by 1
             contains a list of interegers representing an island
        Returns: the perimeeter of the island.
    """

    width = len(grid[0])
    height = len grid
    edge = 0
    size = 0

    for i in range (height):
        for j in range (width):
            if grid[i][j] == 1:
                size += 1
            if (j > 0 and grid[i][j - 1] == 1):
                    edges += 1
                if (i > 0 and grid[i - 1][j] == 1):
                    edges += 1
    return size * 4 - edges * 2
